### PR TITLE
Use CSS in JS and fixed syntax

### PR DESCRIPTION
**Pull request by tascript**
Hi! @litencatt 

I implemented features like

- Use emotion instead of Tailwind CSS
- Fix config
- Fix Props
- Fix Designed
- Delete check box (postscript 2021/10/30)

Please check this Pull Request ☺️ 

## View
スクリーンショット 2021-10-30 17 21 02

### CODE REVIEW

**Comment by tascript** [comment]
I think we need not use checkbox because if we want to invalidate this features, It's better to invalidate this extension.
Therefore I deleted checkbox!

https://github.com/litencatt/paste-string-filter/pull/24/commits/21bd54de576e196db4ce256eb6bc71b7e93862b6

This product changes storage per environment. 
Then, I wondered we can access `chrome.storage` from localhost ? 👀

**Comment by tascript** [comment]
Incidentaly, this commit has already caused that error. 

https://github.com/litencatt/paste-string-filter/commit/fd5cb5349c75cd7d064093b9e68d0a7d7bc3cea0


スクリーンショット 2021-10-30 17 32 39

**Comment by tascript** [comment]
I found the difference of value 👀 
I set `{ enable: 'true' }`

### localStorage

`enabled: "\"true\'"`

### chrome.storage

`enabled: "true"`


But I resolved this problem to delete checkbox 😆

**Comment by litencatt** [comment]
@tascript 
> I think we need not use checkbox because if we want to invalidate this features, It's better to invalidate this extension.
Therefore I deleted checkbox!

この拡張機能はブロッカーじゃなくてあくまでフィルターなんでユーザーが自由にON/OFF可能なほうがいいかなと思っています。さらにはフィルターが増えた場合にフィルター毎にON/OFFは欲しくなる可能性もあります。
なのでできれば残しておきたいです。

> Then, I wondered we can access chrome.storage from localhost ? 👀
StorageExporterを入れて
https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb
ポップアップを検証を開いて以下のようにアクセスすることはできそうです
image
image

**Comment by litencatt** [comment]
https://github.com/litencatt/paste-string-filter/pull/24#issuecomment-955179018

https://stackoverflow.com/questions/24279495/window-localstorage-vs-chrome-storage-local
local storageはstringのみ
chrome storageはJSON互換データが保存可能
という違いがあるようですね

**Comment by tascript** [comment]
@litencatt 

Thanks for your advice 🙏 
I Implemented what we want 🎉 

- add status per list
- keep status

### view

スクリーンショット 2021-11-03 1 46 04

**Review by litencatt — APPROVED** [review]
Thanks😸

**Pull request merged**
